### ISSUE TITLE
新版首页上需有进入原5.0平台各个功能模块及外部链接的链接，并为单点登陆

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-trqgw#12]
原工作流改名为历史流程 ，原邮件改名为历史邮件

**Comment by huangyiirene** [comment]
老平台：
一周会议安排：/hotoa/modules/workschedule/index.jsp
历史邮件：/hotoa/modules/email/index.jsp
历史流程：/hotoa/modules/workflow/index.jsp

**Comment by baozhoutao** [comment]
旧OA单点登录接口：
`Get /hotoa/steedos_accounts_sso.jsp?token=取cookie中的X-Access-Token值&redirect_uri=登录完成后要进入的界面`
