### ISSUE TITLE
管网审批王无法在手机APP中使用，进入一片蓝色

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-trqgw#33]

**Comment by yinlianghui** [comment]
关联任务：[如果定义了 mobile_objects，在手机端自动跳转时，应该跳转到 mobile_objects 的第一个 #1558](https://github.com/steedos/creator/issues/1558)
- 已改为：手机上默认进入第一个应用`审批王`
- 需要打包creator后引用进来才能生效
