### ISSUE TITLE
开发新版门户界面

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-project-trqgw#4]
我觉得最方便的是写一个配置文件用来定义门户。

![image](https://user-images.githubusercontent.com/50353452/64757890-f5935f00-d565-11e9-81da-7fa49f0c7b75.png)

**Comment by baozhoutao** [comment]
[天然气管网-创建首页-公告视图.sql.txt](https://github.com/steedos/steedos-project-trqgw/files/3774418/-.-.sql.txt)
[天然气管网-创建首页-文档，公司信息视图.sql.txt](https://github.com/steedos/steedos-project-trqgw/files/3774419/-.-.sql.txt)

**Comment by baozhoutao** [comment]
[创建首页-公告、公司发文视图.sql.txt](https://github.com/steedos/steedos-project-trqgw/files/3774423/-.sql.txt)
