### ISSUE TITLE
邮件界面优化及整体颜色改为和OA一体的蓝色

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-trqgw#49]
![image](https://user-images.githubusercontent.com/7665279/74899024-a8e66680-53d6-11ea-93f1-75a6bf9fa11a.png)

![image](https://user-images.githubusercontent.com/7665279/74923292-7acf4980-540b-11ea-9a0a-bd61d5dbcf84.png)

**Comment by chenzhipei** [comment]
已处理
