### ISSUE TITLE
系统会自动生成审批岗位，生成的岗位没有所属单位

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-trqgw#5]
9月11日 多了部门经理和分管领导
9月17日 多了部门经理和技术部分管领导

**Comment by yinlianghui** [comment]
这个可能是company_id的遗留问题，导入流程的时候会自动生成审批岗位

**Comment by yinlianghui** [comment]
![image](https://user-images.githubusercontent.com/6219465/72247855-c5052400-3630-11ea-93e2-a494aa04c33f.png)
