### ISSUE TITLE
邮件中需要翻译中文的地方

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-trqgw#56]
![image](https://user-images.githubusercontent.com/7665279/74916126-4904b580-5400-11ea-90f6-8a64dd5ad3a2.png)

删除邮件的提示
![image](https://user-images.githubusercontent.com/7665279/75002048-2de88300-549e-11ea-8e8d-8324d010a605.png)

邮箱授权
![image](https://user-images.githubusercontent.com/7665279/75018740-8fbee200-54ca-11ea-9476-1b5dcc2804ea.png)

**Comment by chenzhipei** [comment]
已添加翻译
