### ISSUE TITLE
Steedos系统和Sogo系统实现单点登录

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-trqgw#6]
配置方案：邮件登陆有效期设置为一年。
可以修改 mailcow.conf
```
# SOGo session timeout in minutes
SOGO_EXPIRE_SESSION=480
```

开发方案：
- 单点登录链接网址：http://{steedos-server}/accounts/authorize?redirect_uri=https://{sogo-server}/sogo-steedos-auth.php
- [/accounts/authorize](https://github.com/steedos/steedos-accounts/blob/master/src/rest-express/endpoints/authorize.ts) 接口，检测用户是否登录
  - 如果未登录则显示登录界面。
  - 如果已登录，则跳转到 redirect_uri 并加上 token 参数，例如：https://{sogo-server}/sogo-steedos-auth.php?token=xxx
- [/sogo-steedos-auth.php](https://github.com/steedos/mailcow-dockerized/blob/steedos/data/web/sogo-steedos-auth.php) 接口，使用token参数连接 steedos 服务器获取当前登录用户的email，使用此email登录进入系统。

**Comment by chenzhipei** [comment]
已处理
